HexBot: 
  General: 
    Client: "HexBot"
    # Don't touch it
    Version: "2.0"
    # Enter your bot token here
    Token: ""
  
  Activity:
    Status: "idle" # online, idle, dnd and invisible
    Message: "/help | 👻"
    # Placeholder: {uptime}, {members}, {servers}, {channels}, {emojis}
    Messages:
      - "100% Power | 👻"
      - "/help | 👻"
      - "CCS_LT#9103 | 👻"
      - "/ping | 👻"
    # "PLAYING", "STREAMING", "WATCHING", "LISTENING" and "CUSTOM_STATUS"
    Type: "PLAYING" 
    # The streaming url of activity 
    # If you set the type = STREAMING
    StreamingURL: "https://www.twitch.tv/hexbot" 
    RandomStatus: true
    # In seconds
    Time: 10

  Guild:
    # Enter your guild id here!
    ID: ""
    # List of owner ids!
    Owner: []
    #  - "459968756416905216"
      
    Channels:
      # These channels allow you to use commands in it!
      WhiteListRoom: []
      #  - "991713970438279180"
      #  - "948425289598378037"
      # Channels that allow the use of the command (/crash)
      CrashRoom: []
      #  - "991713970438279180"
      # These channels notify the proxy auto update!
      # Need AutoUpdate: true to work!
      UpdateRoom: []
      #  - "991713970438279180"
      #  - "1001429639887077436"
    
    # Explain the role of commands and methods!
    # Role priority: Admin -> Premium -> Basic
    # 
    # When Role: Basic -> All 3 role types can be used (Admin, Premium, Basic)
    # When Role: Premium -> All 2 role types can be used (Admin, Premium)
    # When Role: Admin -> All 1 role types can be used (Admin)
    Roles:
      # List admin role ids
      Admin: []
      #  - "948518823672311818"
      # List premium role ids
      Premium: []
      #  - "1000647557074141194"
      # List basic role ids
      Basic: [] 
      #  - "1000647643166425188"
  
  Update: 
    # Should update on startup be enabled!
    # If enabled, it will update itself every time you start up
    UpdateOnStartUp: false
    # Should the auto-update feature be enabled?
    AutoUpdate: false
    # Time automatically updated each time. In seconds!
    Time: 900
    # Mode of update:
    # USER -> User needs to enter URL to update!
    # URL -> Use the URL available in the config!
    # BOTH -> If a user enters a URL, that user's URL will be used!
    #  If the user does not enter the URL, the URL available in the configuration will be used!
    Mode: BOTH
    # Proxy file name
    FileName: "proxies.txt"
    # Proxy update url
    URL: 
      - "https://api.openproxylist.xyz/socks4.txt"
      - "https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/socks4.txt"
      - "https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/socks4.txt"
      - "https://raw.githubusercontent.com/rdavydov/proxy-list/main/proxies/socks4.txt"
      - "https://raw.githubusercontent.com/roosterkid/openproxylist/main/SOCKS4_RAW.txt"
      - "https://raw.githubusercontent.com/saschazesiger/Free-Proxies/master/proxies/socks4.txt"
      - "https://raw.githubusercontent.com/UptimerBot/proxy-list/main/proxies/socks4.txt"
      - "https://proxyspace.pro/socks4.txt"
      - "https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/socks4.txt"
      - "https://raw.githubusercontent.com/monosans/proxy-list/main/proxies_anonymous/socks4.txt"
      - "https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies-socks4.txt"
      - "https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/socks4.txt"
      - "http://worm.rip/socks4.txt"
      - "https://www.proxy-list.download/api/v1/get?type=socks4"
      - "https://raw.githubusercontent.com/HyperBeats/proxy-list/main/socks4.txt"
      - "https://raw.githubusercontent.com/mmpx12/proxy-list/master/socks4.txt"
      - "https://raw.githubusercontent.com/saschazesiger/Free-Proxies/master/proxies/socks4.txt"
      - "https://raw.githubusercontent.com/B4RC0DE-TM/proxy-list/main/SOCKS4.txt"
  
  # This feature will automatically download java for bot, very useful when using on host/node
  AutoDownloadJava: 
    # Should java auto-download feature be enabled!
    Enabled: true
    # URL to download java
    URL: "https://builds.openlogic.com/downloadJDK/openlogic-openjdk/8u262-b10/openlogic-openjdk-8u262-b10-linux-x64.tar.gz"
    
  Buttons: 
    # Specify IDs for buttons!
    Config: 
      StopAttackEmbed: "crash-stopattack"
      StopConfirm: "stopconfirm-accept"
      StopCancel: "stopconfirm-cancel"
    # Don't change the CustomID!
    Commands: 
      Stop: 
        Confirm: 
          - Label: "Accept"
            Style: "SUCCESS"
            Emoji: "1000711650296463360"
            CustomID: "stopconfirm-accept"
          - Label: "Cancel"
            Style: "DANGER"
            Emoji: "1000337855555588188"
            CustomID: "stopconfirm-cancel" 
      Crash: 
        Stop: 
          - Label: "Stop Attack!"
            Style: "DANGER"
            Emoji: "1000566539885490257"
            CustomID: "crash-stopattack"
  DropdownMenu: 
    Config: 
      SelectMethodsType: 
        All: "methodstype-all"
        Admin: "methodstype-admin"
        Premium: "methodstype-premium"
        Basic: "methodstype-basic"
    Commands: 
      Methods: 
        SelectType: 
          CustomID: "methodstype-select"
          Placeholder: "Click to select type of methods!"
          Options: 
            - Label: "Type - All"
              Description: "List all available methods!"
              Value: "methodstype-all"
              Emoji: "1000345453927350283"
            - Label: "Type - Admin"
              Description: "Listed all methods with type admin!"
              Value: "methodstype-admin"
              Emoji: "1000345453927350283"
            - Label: "Type - Premium"
              Description: "Listed all methods with type premium!"
              Value: "methodstype-premium"
              Emoji: "1000345453927350283"
            - Label: "Type - Basic"
              Description: "Listed all methods with type basic!"
              Value: "methodstype-basic"
              Emoji: "1000345453927350283"

  TimeForRole: 
    # -1 for unlimited
    Admin: 
      Min: -1
      Max: -1
    Premium: 
      Min: 60
      Max: 180
    Basic: 
      Min: 60
      Max: 120
  
        